# """add banners table

# Revision ID: 304fb6eed585
# Revises: 0005
# Create Date: 2026-08-10 12:05:13.972743

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql

# # revision identifiers, used by Alembic.
# revision: str = '304fb6eed585'
# down_revision: Union[str, None] = '0005'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('banners',
#     sa.Column('id', app.db.types.GUID(), nullable=False),
#     sa.Column('title', sa.String(length=200), nullable=False),
#     sa.Column('subtitle', sa.String(length=500), nullable=True),
#     sa.Column('image_url', sa.String(length=500), nullable=False),
#     sa.Column('link_url', sa.String(length=500), nullable=True),
#     sa.Column('display_order', sa.Integer(), nullable=False),
#     sa.Column('is_active', sa.Boolean(), nullable=False),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.alter_column('addresses', 'label',
#                existing_type=sa.VARCHAR(length=50),
#                nullable=False,
#                existing_server_default=sa.text("'Home'::character varying"))
#     op.alter_column('addresses', 'country',
#                existing_type=sa.VARCHAR(length=100),
#                nullable=False,
#                existing_server_default=sa.text("'India'::character varying"))
#     op.alter_column('addresses', 'is_default',
#                existing_type=sa.BOOLEAN(),
#                nullable=False,
#                existing_server_default=sa.text('false'))
#     op.alter_column('addresses', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('brands', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('cart_items', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('carts', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('carts', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('categories', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('coupons', 'min_order_value',
#                existing_type=sa.NUMERIC(precision=10, scale=2),
#                nullable=False,
#                existing_server_default=sa.text("'0'::numeric"))
#     op.alter_column('coupons', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('delivery_partners', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('notifications', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('orders', 'discount_amount',
#                existing_type=sa.NUMERIC(precision=10, scale=2),
#                nullable=False,
#                existing_server_default=sa.text("'0'::numeric"))
#     op.alter_column('orders', 'gst_amount',
#                existing_type=sa.NUMERIC(precision=10, scale=2),
#                nullable=False,
#                existing_server_default=sa.text("'0'::numeric"))
#     op.alter_column('orders', 'shipping_charge',
#                existing_type=sa.NUMERIC(precision=10, scale=2),
#                nullable=False,
#                existing_server_default=sa.text("'0'::numeric"))
#     op.alter_column('orders', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('orders', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('payments', 'currency',
#                existing_type=sa.VARCHAR(length=10),
#                nullable=False,
#                existing_server_default=sa.text("'INR'::character varying"))
#     op.alter_column('payments', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('payments', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('product_images', 'is_primary',
#                existing_type=sa.BOOLEAN(),
#                nullable=False,
#                existing_server_default=sa.text('false'))
#     op.alter_column('product_images', 'display_order',
#                existing_type=sa.INTEGER(),
#                nullable=False,
#                existing_server_default=sa.text('0'))
#     op.alter_column('product_images', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('product_variants', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('products', 'discount_percentage',
#                existing_type=sa.NUMERIC(precision=5, scale=2),
#                nullable=False,
#                existing_server_default=sa.text("'0'::numeric"))
#     op.alter_column('products', 'gst_percentage',
#                existing_type=sa.NUMERIC(precision=5, scale=2),
#                nullable=False,
#                existing_server_default=sa.text("'0'::numeric"))
#     op.alter_column('products', 'is_featured',
#                existing_type=sa.BOOLEAN(),
#                nullable=False,
#                existing_server_default=sa.text('false'))
#     op.alter_column('products', 'is_trending',
#                existing_type=sa.BOOLEAN(),
#                nullable=False,
#                existing_server_default=sa.text('false'))
#     op.alter_column('products', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('products', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('reviews', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('search_queries', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('search_queries', 'last_searched_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('tracking_events', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('users', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('users', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=False,
#                existing_server_default=sa.text('now()'))
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('users', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('users', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('tracking_events', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('search_queries', 'last_searched_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('search_queries', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('reviews', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('products', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('products', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('products', 'is_trending',
#                existing_type=sa.BOOLEAN(),
#                nullable=True,
#                existing_server_default=sa.text('false'))
#     op.alter_column('products', 'is_featured',
#                existing_type=sa.BOOLEAN(),
#                nullable=True,
#                existing_server_default=sa.text('false'))
#     op.alter_column('products', 'gst_percentage',
#                existing_type=sa.NUMERIC(precision=5, scale=2),
#                nullable=True,
#                existing_server_default=sa.text("'0'::numeric"))
#     op.alter_column('products', 'discount_percentage',
#                existing_type=sa.NUMERIC(precision=5, scale=2),
#                nullable=True,
#                existing_server_default=sa.text("'0'::numeric"))
#     op.alter_column('product_variants', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('product_images', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('product_images', 'display_order',
#                existing_type=sa.INTEGER(),
#                nullable=True,
#                existing_server_default=sa.text('0'))
#     op.alter_column('product_images', 'is_primary',
#                existing_type=sa.BOOLEAN(),
#                nullable=True,
#                existing_server_default=sa.text('false'))
#     op.alter_column('payments', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('payments', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('payments', 'currency',
#                existing_type=sa.VARCHAR(length=10),
#                nullable=True,
#                existing_server_default=sa.text("'INR'::character varying"))
#     op.alter_column('orders', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('orders', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('orders', 'shipping_charge',
#                existing_type=sa.NUMERIC(precision=10, scale=2),
#                nullable=True,
#                existing_server_default=sa.text("'0'::numeric"))
#     op.alter_column('orders', 'gst_amount',
#                existing_type=sa.NUMERIC(precision=10, scale=2),
#                nullable=True,
#                existing_server_default=sa.text("'0'::numeric"))
#     op.alter_column('orders', 'discount_amount',
#                existing_type=sa.NUMERIC(precision=10, scale=2),
#                nullable=True,
#                existing_server_default=sa.text("'0'::numeric"))
#     op.alter_column('notifications', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('delivery_partners', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('coupons', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('coupons', 'min_order_value',
#                existing_type=sa.NUMERIC(precision=10, scale=2),
#                nullable=True,
#                existing_server_default=sa.text("'0'::numeric"))
#     op.alter_column('categories', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('carts', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('carts', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('cart_items', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('brands', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('addresses', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                nullable=True,
#                existing_server_default=sa.text('now()'))
#     op.alter_column('addresses', 'is_default',
#                existing_type=sa.BOOLEAN(),
#                nullable=True,
#                existing_server_default=sa.text('false'))
#     op.alter_column('addresses', 'country',
#                existing_type=sa.VARCHAR(length=100),
#                nullable=True,
#                existing_server_default=sa.text("'India'::character varying"))
#     op.alter_column('addresses', 'label',
#                existing_type=sa.VARCHAR(length=50),
#                nullable=True,
#                existing_server_default=sa.text("'Home'::character varying"))
#     op.drop_table('banners')
#     # ### end Alembic commands ###




"""add banners table

Revision ID: 304fb6eed585
Revises: 0005
Create Date: 2026-08-10
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.types import GUID


# revision identifiers, used by Alembic.
revision: str = "304fb6eed585"
down_revision: Union[str, None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "banners",
        sa.Column(
            "id",
            GUID(),
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(length=200),
            nullable=False,
        ),
        sa.Column(
            "subtitle",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "image_url",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "link_url",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "display_order",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=True,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("banners")